p8105_hw1_jq2342
================
2022-09-22

**QUESTION 1**

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.1      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
data("penguins", package = "palmerpenguins")
df=penguins
ls(df)
```

    ## [1] "bill_depth_mm"     "bill_length_mm"    "body_mass_g"      
    ## [4] "flipper_length_mm" "island"            "sex"              
    ## [7] "species"           "year"

``` r
nrow(df) 
```

    ## [1] 344

``` r
ncol(df)
```

    ## [1] 8

``` r
mean(df$flipper_length_mm, na.rm=TRUE)
```

    ## [1] 200.9152

\##1. The penguins data includes the species, island, length and depth
of the bill, length of the flippers, body mass, sex and year. \##2.
There are 8 variables(column) and 344 observations(row) \##3. The mean
for flipper_length_mm is 200.9152

``` r
ggplot(df, aes(x=bill_length_mm, y=flipper_length_mm, color=species,na.rm=TRUE)) + geom_point(na.rm=TRUE)
```

![](p8105_hw1_jq2342_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
ggsave("df.png")
```

    ## Saving 7 x 5 in image

**QUESTION 2**

``` r
hw1_df=tibble (  
vec_ran=rnorm(n=10),
vec_logi=vec_ran>0,
vec_char=(c("this", "is", "a", "character", "vector", "for", "the", "home", "work", "two")),
vec_fac=factor(c("one","two","three","one","two","three","one","two","three","one"))
)
```

``` r
mean(hw1_df$vec_ran, na.rm=TRUE)
```

    ## [1] 0.3172563

``` r
mean(hw1_df$vec_logi, na.rm=TRUE)
```

    ## [1] 0.6

``` r
mean(hw1_df$vec_char, na.rm=TRUE)
```

    ## Warning in mean.default(hw1_df$vec_char, na.rm = TRUE): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
mean(hw1_df$vec_fac, na.rm=TRUE)
```

    ## Warning in mean.default(hw1_df$vec_fac, na.rm = TRUE): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

\##the mean of vec_ran is 0.152 \##the mean of vec_logi is 0.3, there
should not be a mean for the logical since true and false do not have
numeric value, however r treats TRUE as 1 and FALSE as 0. \##the mean of
vec_char is not applicable because character variable doesn’ have a
numeric value \##the mean of vec_fac is not applicable because string
variable doesn’ have a numeric value

``` r
hw1_df$vec_char = as.numeric(as.character(hw1_df$vec_char)) 
```

    ## Warning: NAs introduced by coercion

``` r
hw1_df$vec_logi = as.numeric(as.character(hw1_df$vec_logi)) 
```

    ## Warning: NAs introduced by coercion

``` r
hw1_df$vec_fac = as.numeric(as.character(hw1_df$vec_fac)) 
```

    ## Warning: NAs introduced by coercion

``` r
print (sapply(hw1_df, class))
```

    ##   vec_ran  vec_logi  vec_char   vec_fac 
    ## "numeric" "numeric" "numeric" "numeric"

\##after applying as.numeric to the non-numeric variables, they are
changed into numeric variables.This explain why the mean for those
variable are not applicable since they weren’t numeric
